// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_proyect_rebajaon_app/test/controller/alerta_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_proyect_rebajaon_app/DAO/alerta_dao.dart' as _i2;
import 'package:flutter_proyect_rebajaon_app/models/alerta_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AlertaDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertaDao extends _i1.Mock implements _i2.AlertaDao {
  MockAlertaDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertarAlerta(_i4.AlertaModel? alerta) =>
      (super.noSuchMethod(
            Invocation.method(#insertarAlerta, [alerta]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.AlertaModel>> listarAlertas() =>
      (super.noSuchMethod(
            Invocation.method(#listarAlertas, []),
            returnValue: _i3.Future<List<_i4.AlertaModel>>.value(
              <_i4.AlertaModel>[],
            ),
          )
          as _i3.Future<List<_i4.AlertaModel>>);

  @override
  _i3.Future<bool> existeAlertaActiva({
    required int? idMedicamento,
    required String? tipo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#existeAlertaActiva, [], {
              #idMedicamento: idMedicamento,
              #tipo: tipo,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> resolverAlertasActivas({
    required int? idMedicamento,
    required String? tipo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolverAlertasActivas, [], {
              #idMedicamento: idMedicamento,
              #tipo: tipo,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> actualizarAlertaActiva({
    required int? idMedicamento,
    required String? tipo,
    required String? nivelGravedad,
    required String? mensaje,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarAlertaActiva, [], {
              #idMedicamento: idMedicamento,
              #tipo: tipo,
              #nivelGravedad: nivelGravedad,
              #mensaje: mensaje,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
