// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_proyect_rebajaon_app/test/controller/medicamento_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_proyect_rebajaon_app/DAO/lote_dao.dart' as _i5;
import 'package:flutter_proyect_rebajaon_app/DAO/medicamento_dao.dart' as _i2;
import 'package:flutter_proyect_rebajaon_app/models/lote_model.dart' as _i6;
import 'package:flutter_proyect_rebajaon_app/models/medicamento_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MedicamentoDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicamentoDao extends _i1.Mock implements _i2.MedicamentoDao {
  MockMedicamentoDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertarMedicamento(_i4.MedicamentoModel? medicamento) =>
      (super.noSuchMethod(
            Invocation.method(#insertarMedicamento, [medicamento]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.MedicamentoModel>> listarMedicamentos() =>
      (super.noSuchMethod(
            Invocation.method(#listarMedicamentos, []),
            returnValue: _i3.Future<List<_i4.MedicamentoModel>>.value(
              <_i4.MedicamentoModel>[],
            ),
          )
          as _i3.Future<List<_i4.MedicamentoModel>>);

  @override
  _i3.Future<_i4.MedicamentoModel?> buscarPorNombre(String? nombre) =>
      (super.noSuchMethod(
            Invocation.method(#buscarPorNombre, [nombre]),
            returnValue: _i3.Future<_i4.MedicamentoModel?>.value(),
          )
          as _i3.Future<_i4.MedicamentoModel?>);

  @override
  _i3.Future<_i4.MedicamentoModel?> buscarPorId(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#buscarPorId, [id]),
            returnValue: _i3.Future<_i4.MedicamentoModel?>.value(),
          )
          as _i3.Future<_i4.MedicamentoModel?>);
}

/// A class which mocks [LoteDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoteDao extends _i1.Mock implements _i5.LoteDao {
  MockLoteDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertarLote(_i6.LoteModel? lote) =>
      (super.noSuchMethod(
            Invocation.method(#insertarLote, [lote]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> actualizarStockMedicamento(int? idMedicamento) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarStockMedicamento, [idMedicamento]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> descontarStockPorCantidad(
    String? codigoBarras,
    int? cantidad,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descontarStockPorCantidad, [
              codigoBarras,
              cantidad,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i6.LoteModel>> listarLotesPorMedicamento(
    int? idMedicamento,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listarLotesPorMedicamento, [idMedicamento]),
            returnValue: _i3.Future<List<_i6.LoteModel>>.value(
              <_i6.LoteModel>[],
            ),
          )
          as _i3.Future<List<_i6.LoteModel>>);

  @override
  _i3.Future<List<_i6.LoteModel>> listarLotes() =>
      (super.noSuchMethod(
            Invocation.method(#listarLotes, []),
            returnValue: _i3.Future<List<_i6.LoteModel>>.value(
              <_i6.LoteModel>[],
            ),
          )
          as _i3.Future<List<_i6.LoteModel>>);

  @override
  _i3.Future<_i6.LoteModel?> buscarPorCodigoBarras(String? codigoBarras) =>
      (super.noSuchMethod(
            Invocation.method(#buscarPorCodigoBarras, [codigoBarras]),
            returnValue: _i3.Future<_i6.LoteModel?>.value(),
          )
          as _i3.Future<_i6.LoteModel?>);

  @override
  _i3.Future<void> descontarStock(String? codigoBarras) =>
      (super.noSuchMethod(
            Invocation.method(#descontarStock, [codigoBarras]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
