// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_proyect_rebajaon_app/test/controller/reporte_dao_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_proyect_rebajaon_app/DAO/reporte_dao.dart' as _i3;
import 'package:flutter_proyect_rebajaon_app/models/reporte_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReporteResumenModel_0 extends _i1.SmartFake
    implements _i2.ReporteResumenModel {
  _FakeReporteResumenModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReporteDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockReporteDao extends _i1.Mock implements _i3.ReporteDao {
  MockReporteDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ReporteResumenModel> obtenerResumen() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerResumen, []),
            returnValue: _i4.Future<_i2.ReporteResumenModel>.value(
              _FakeReporteResumenModel_0(
                this,
                Invocation.method(#obtenerResumen, []),
              ),
            ),
          )
          as _i4.Future<_i2.ReporteResumenModel>);

  @override
  _i4.Future<List<_i2.ReporteVentaProductoModel>> productosMasVendidos({
    DateTime? fechaDesde,
    DateTime? fechaHasta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#productosMasVendidos, [], {
              #fechaDesde: fechaDesde,
              #fechaHasta: fechaHasta,
            }),
            returnValue: _i4.Future<List<_i2.ReporteVentaProductoModel>>.value(
              <_i2.ReporteVentaProductoModel>[],
            ),
          )
          as _i4.Future<List<_i2.ReporteVentaProductoModel>>);

  @override
  _i4.Future<List<_i2.ReporteAlertaModel>> resumenAlertas() =>
      (super.noSuchMethod(
            Invocation.method(#resumenAlertas, []),
            returnValue: _i4.Future<List<_i2.ReporteAlertaModel>>.value(
              <_i2.ReporteAlertaModel>[],
            ),
          )
          as _i4.Future<List<_i2.ReporteAlertaModel>>);

  @override
  _i4.Future<List<_i2.ReporteLoteModel>> lotesRegistrados() =>
      (super.noSuchMethod(
            Invocation.method(#lotesRegistrados, []),
            returnValue: _i4.Future<List<_i2.ReporteLoteModel>>.value(
              <_i2.ReporteLoteModel>[],
            ),
          )
          as _i4.Future<List<_i2.ReporteLoteModel>>);

  @override
  _i4.Future<List<_i2.ReporteInventarioModel>> inventarioActual() =>
      (super.noSuchMethod(
            Invocation.method(#inventarioActual, []),
            returnValue: _i4.Future<List<_i2.ReporteInventarioModel>>.value(
              <_i2.ReporteInventarioModel>[],
            ),
          )
          as _i4.Future<List<_i2.ReporteInventarioModel>>);
}
