// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_proyect_rebajaon_app/test/controller/ventas_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_proyect_rebajaon_app/Controllers/alerta_controller.dart'
    as _i11;
import 'package:flutter_proyect_rebajaon_app/DAO/alerta_dao.dart' as _i2;
import 'package:flutter_proyect_rebajaon_app/DAO/carrito_dao.dart' as _i10;
import 'package:flutter_proyect_rebajaon_app/DAO/lote_dao.dart' as _i6;
import 'package:flutter_proyect_rebajaon_app/DAO/scanner_dao.dart' as _i3;
import 'package:flutter_proyect_rebajaon_app/DAO/ventas_dao.dart' as _i8;
import 'package:flutter_proyect_rebajaon_app/models/lote_model.dart' as _i7;
import 'package:flutter_proyect_rebajaon_app/models/scanner_model.dart' as _i5;
import 'package:flutter_proyect_rebajaon_app/models/ventas_model.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAlertaDao_0 extends _i1.SmartFake implements _i2.AlertaDao {
  _FakeAlertaDao_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ScannerDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockScannerDao extends _i1.Mock implements _i3.ScannerDao {
  MockScannerDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ScannerModel?> buscarPorCodigo(String? codigoBarras) =>
      (super.noSuchMethod(
            Invocation.method(#buscarPorCodigo, [codigoBarras]),
            returnValue: _i4.Future<_i5.ScannerModel?>.value(),
          )
          as _i4.Future<_i5.ScannerModel?>);

  @override
  _i4.Future<List<_i5.ScannerModel>> buscarPorNombre(String? nombre) =>
      (super.noSuchMethod(
            Invocation.method(#buscarPorNombre, [nombre]),
            returnValue: _i4.Future<List<_i5.ScannerModel>>.value(
              <_i5.ScannerModel>[],
            ),
          )
          as _i4.Future<List<_i5.ScannerModel>>);

  @override
  _i4.Future<List<_i5.ScannerModel>> listarMedicamentosDisponibles() =>
      (super.noSuchMethod(
            Invocation.method(#listarMedicamentosDisponibles, []),
            returnValue: _i4.Future<List<_i5.ScannerModel>>.value(
              <_i5.ScannerModel>[],
            ),
          )
          as _i4.Future<List<_i5.ScannerModel>>);
}

/// A class which mocks [LoteDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoteDao extends _i1.Mock implements _i6.LoteDao {
  MockLoteDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insertarLote(_i7.LoteModel? lote) =>
      (super.noSuchMethod(
            Invocation.method(#insertarLote, [lote]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> actualizarStockMedicamento(int? idMedicamento) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarStockMedicamento, [idMedicamento]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> descontarStockPorCantidad(
    String? codigoBarras,
    int? cantidad,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descontarStockPorCantidad, [
              codigoBarras,
              cantidad,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.LoteModel>> listarLotesPorMedicamento(
    int? idMedicamento,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listarLotesPorMedicamento, [idMedicamento]),
            returnValue: _i4.Future<List<_i7.LoteModel>>.value(
              <_i7.LoteModel>[],
            ),
          )
          as _i4.Future<List<_i7.LoteModel>>);

  @override
  _i4.Future<List<_i7.LoteModel>> listarLotes() =>
      (super.noSuchMethod(
            Invocation.method(#listarLotes, []),
            returnValue: _i4.Future<List<_i7.LoteModel>>.value(
              <_i7.LoteModel>[],
            ),
          )
          as _i4.Future<List<_i7.LoteModel>>);

  @override
  _i4.Future<_i7.LoteModel?> buscarPorCodigoBarras(String? codigoBarras) =>
      (super.noSuchMethod(
            Invocation.method(#buscarPorCodigoBarras, [codigoBarras]),
            returnValue: _i4.Future<_i7.LoteModel?>.value(),
          )
          as _i4.Future<_i7.LoteModel?>);

  @override
  _i4.Future<void> descontarStock(String? codigoBarras) =>
      (super.noSuchMethod(
            Invocation.method(#descontarStock, [codigoBarras]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [VentaDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockVentaDao extends _i1.Mock implements _i8.VentaDao {
  MockVentaDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> registrarVenta({
    required int? idUsuario,
    required int? idCarrito,
    required double? total,
    required List<_i9.VentaItemModel>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarVenta, [], {
              #idUsuario: idUsuario,
              #idCarrito: idCarrito,
              #total: total,
              #items: items,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [CarritoDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarritoDao extends _i1.Mock implements _i10.CarritoDao {
  MockCarritoDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> crearCarrito(int? idUsuario) =>
      (super.noSuchMethod(
            Invocation.method(#crearCarrito, [idUsuario]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> guardarDetalleCarrito({
    required int? idCarrito,
    required List<_i9.VentaItemModel>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#guardarDetalleCarrito, [], {
              #idCarrito: idCarrito,
              #items: items,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmarCarrito(int? idCarrito) =>
      (super.noSuchMethod(
            Invocation.method(#confirmarCarrito, [idCarrito]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AlertaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertaController extends _i1.Mock implements _i11.AlertaController {
  MockAlertaController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AlertaDao get alertaDao =>
      (super.noSuchMethod(
            Invocation.getter(#alertaDao),
            returnValue: _FakeAlertaDao_0(this, Invocation.getter(#alertaDao)),
          )
          as _i2.AlertaDao);

  @override
  _i4.Future<String?> generarAlertaCadenaFrio({
    required int? idMedicamento,
    required String? nombreMedicamento,
    required double? temperatura,
    required double? rangoMin,
    required double? rangoMax,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generarAlertaCadenaFrio, [], {
              #idMedicamento: idMedicamento,
              #nombreMedicamento: nombreMedicamento,
              #temperatura: temperatura,
              #rangoMin: rangoMin,
              #rangoMax: rangoMax,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> generarAlertaStockMinimo({
    required int? idMedicamento,
    required String? nombreMedicamento,
    required int? stockActual,
    required int? stockMinimo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generarAlertaStockMinimo, [], {
              #idMedicamento: idMedicamento,
              #nombreMedicamento: nombreMedicamento,
              #stockActual: stockActual,
              #stockMinimo: stockMinimo,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> generarAlertaVencimientoProximo({
    required int? idMedicamento,
    required int? idLote,
    required String? nombreMedicamento,
    required DateTime? fechaVencimiento,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generarAlertaVencimientoProximo, [], {
              #idMedicamento: idMedicamento,
              #idLote: idLote,
              #nombreMedicamento: nombreMedicamento,
              #fechaVencimiento: fechaVencimiento,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> generarAlertaMedicamentoVencido({
    required int? idMedicamento,
    required int? idLote,
    required String? nombreMedicamento,
    required DateTime? fechaVencimiento,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generarAlertaMedicamentoVencido, [], {
              #idMedicamento: idMedicamento,
              #idLote: idLote,
              #nombreMedicamento: nombreMedicamento,
              #fechaVencimiento: fechaVencimiento,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> resolverAlertaStockMinimoSiCorresponde({
    required int? idMedicamento,
    required int? stockActual,
    required int? stockMinimo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolverAlertaStockMinimoSiCorresponde, [], {
              #idMedicamento: idMedicamento,
              #stockActual: stockActual,
              #stockMinimo: stockMinimo,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
